doctrine:
    dbal:
        default_connection: mariadb
        connections:
            mariadb:
                url: '%env(resolve:MARIADB_URL)%'
            postgres:
                url: '%env(resolve:POSTGRES_URL)%'
